[package]
authors = ["Wilson Lin <code@wilsonl.in>"]
categories = [
    "compression",
    "command-line-utilities",
    "development-tools::build-utils",
    "web-programming",
]
description = "Extremely fast JavaScript minifier"
edition = "2021"
homepage = "https://github.com/wilsonzlin/minify-js"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
keywords = ["javascript", "compress", "minifier", "js", "ecmascript"]
license = "Apache-2.0"
name = "minify-js"
readme = "README.md"
repository = "https://github.com/wilsonzlin/minify-js"
version = "0.6.1"

[dependencies]
aho-corasick = "0.7"
lazy_static = "1.4"
parse-js = "0.21"

[features]
serialize = ["parse-js/serialize"]
